---
steps:
  update:
    image: python:3.12-alpine
    commands: python scripts/update.py
    when:
      - event: cron
        cron: update plugins
      - event: [push, pull_request]
        branch: main

  push:
    image: appleboy/drone-git-push
    settings:
      branch: main
      remote:
        from_secret: codeberg_repository
      force: true
      commit: true
    when:
      - event: cron
        cron: update plugins
      - event: [push, pull_request]
        branch: main
